print("hello!")
print("* * * * * * * *")
print("*             *")
print("*             *")
print("*             *")
print("*             *")
print("*             *")
print("*             *")
print("* * * * * * * *")
print("* * * * * * * *")

print("**")
print("*  *")
print("*    *")
print("*      *")
print("*        *")
print("*          *")
print("*            *")
print("***************")
print("* * * * * * * *")

print("       *       ")
print("      * *      ")
print("     * * *     ")
print("    * * * *    ")
print("   * * * * *   ")
print("  * * * * * *  ")
print(" * * * * * * * ")
